from pydantic import Field, BaseModel
from typing import List, Optional, Literal
import pandas as pd
from dotenv import load_dotenv
import os
from typing import TypedDict, Annotated
from langchain_community.document_loaders.csv_loader import CSVLoader
from langchain_core.messages import (
    SystemMessage,
    BaseMessage,
    HumanMessage,
    ToolMessage,
)
from langchain_core.output_parsers import PydanticOutputParser
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import InMemorySaver
import asyncio
from langchain_mcp_adapters.client import MultiServerMCPClient

load_dotenv()


async def load_tools():
    servers = {
        "python_tools": {
            "transport": "stdio",
            "command": "uv",
            "args": [
                "run",
                "fastmcp",
                "run",
                "C:\\Users\\panka\\genai_project\\data_analysis_agent\\mcp_server\\main.py",
            ],
        }
    }

    client = MultiServerMCPClient(servers)
    tools = await client.get_tools()
    return tools


tools = asyncio.run(load_tools())
tools = [i for i in tools if i.name == "run_pandas_queries"]

model_for_query_executor = ChatNVIDIA(
    model="mistralai/mistral-small-4-119b-2603", max_completion_tokens=10000
).bind_tools(tools)


class schema_for_pandas_query_formatter(BaseModel):
    query: str = Field(..., description="query")
    result: str = Field(..., description="result")


parser_for_pandas_query_formatter = PydanticOutputParser(
    pydantic_object=schema_for_pandas_query_formatter
)


class schema_for_pandas_query_executor(TypedDict):
    messages: Annotated[BaseMessage, add_messages]
    query: str
    formatted_result: schema_for_pandas_query_formatter


sys_prompt_for_pandas_query_executor = """
You are an data analyst . User will provide you a task and a csv schema Your task is to write and execute a single line/multi line pandas queries to acheive the desired output.
"""


def chat_node_for_pandas_query_executor(state: schema_for_pandas_query_executor):
    pr = [
        SystemMessage(content=sys_prompt_for_pandas_query_executor),
        *state["messages"],
    ]
    res = model_for_query_executor.invoke(pr)

    return {"messages": [res]}


sys_prompt_for_pandas_query_formatter = f"""
User will provide you an query and the answer generated by user for the given query your task is to format it into given format -
{parser_for_pandas_query_formatter.get_format_instructions()}
"""


def pandas_query_formator(state: schema_for_pandas_query_executor):
    pr = [
        SystemMessage(content=sys_prompt_for_pandas_query_formatter),
        HumanMessage(content=f"""
    query - {state['query']} 
    result - {state['messages'][-1].content}
    """),
    ]

    res = model_for_query_executor.invoke(pr)
    res = parser_for_pandas_query_formatter.invoke(res.content)
    return {"formatted_result": res}



def tool_call_condition(
    state: schema_for_pandas_query_executor,
) -> Literal["tools", "schema_formatter"]:
    if state["messages"][-1].tool_calls:
        return "tools"
    return "schema_formatter"


graph = StateGraph(schema_for_pandas_query_executor)

graph.add_node("chat_node", chat_node_for_pandas_query_executor)
graph.add_node("schema_formatter", pandas_query_formator)
graph.add_node("tools", ToolNode(tools))

graph.add_edge(START, "chat_node")
graph.add_conditional_edges("chat_node", tool_call_condition)
graph.add_edge("tools", "chat_node")

workflow_for_pandas_query = graph.compile()








# csv_schema="""{ "properties": { "file_level_metadata": { "properties": { "total_rows": { "title": "Total Rows", "type": "integer" }, "total_columns": { "title": "Total Columns", "type": "integer" }, "duplicate_row_count": { "title": "Duplicate Row Count", "type": "integer" } }, "required": ["total_rows", "total_columns", "duplicate_row_count"] }, "per_column_details": { "type": "object", "properties": { "Id": { "properties": { "column_name": { "title": "Column Name", "type": "string" }, "data_type": { "title": "Data Type", "type": "string" }, "semantic_type": { "title": "Semantic Type", "type": "string" }, "sample_values": { "type": "array", "items": { "type": "number" } }, "null_count": { "title": "Null Count", "type": "integer" }, "null_percentage": { "type": "number", "description": "between 0.0 and 100.0" }, "unique_value_count": { "title": "Unique Value Count", "type": "integer" }, "range": { "type": "object", "properties": { "min": { "type": "number" }, "max": { "type": "number" } } }, "description": { "title": "Description", "type": "string" } }, "required": ["column_name", "data_type", "semantic_type", "sample_values", "null_count", "null_percentage", "unique_value_count", "range", "description"] }, "SepalLengthCm": { "properties": { "column_name": { "title": "Column Name", "type": "string" }, "data_type": { "title": "Data Type", "type": "string" }, "semantic_type": { "title": "Semantic Type", "type": "string" }, "sample_values": { "type": "array", "items": { "type": "number" } }, "null_count": { "title": "Null Count", "type": "integer" }, "null_percentage": { "type": "number", "description": "between 0.0 and 100.0" }, "unique_value_count": { "title": "Unique Value Count", "type": "integer" }, "range": { "type": "object", "properties": { "min": { "type": "number" }, "max": { "type": "number" } } }, "description": { "title": "Description", "type": "string" } }, "required": ["column_name", "data_type", "semantic_type", "sample_values", "null_count", "null_percentage", "unique_value_count", "range", "description"] }, "SepalWidthCm": { "properties": { "column_name": { "title": "Column Name", "type": "string" }, "data_type": { "title": "Data Type", "type": "string" }, "semantic_type": { "title": "Semantic Type", "type": "string" }, "sample_values": { "type": "array", "items": { "type": "number" } }, "null_count": { "title": "Null Count", "type": "integer" }, "null_percentage": { "type": "number", "description": "between 0.0 and 100.0" }, "unique_value_count": { "title": "Unique Value Count", "type": "integer" }, "range": { "type": "object", "properties": { "min": { "type": "number" }, "max": { "type": "number" } } }, "description": { "title": "Description", "type": "string" } }, "required": ["column_name", "data_type", "semantic_type", "sample_values", "null_count", "null_percentage", "unique_value_count", "range", "description"] }, "PetalLengthCm": { "properties": { "column_name": { "title": "Column Name", "type": "string" }, "data_type": { "title": "Data Type", "type": "string" }, "semantic_type": { "title": "Semantic Type", "type": "string" }, "sample_values": { "type": "array", "items": { "type": "number" } }, "null_count": { "title": "Null Count", "type": "integer" }, "null_percentage": { "type": "number", "description": "between 0.0 and 100.0" }, "unique_value_count": { "title": "Unique Value Count", "type": "integer" }, "range": { "type": "object", "properties": { "min": { "type": "number" }, "max": { "type": "number" } } }, "description": { "title": "Description", "type": "string" } }, "required": ["column_name", "data_type", "semantic_type", "sample_values", "null_count", "null_percentage", "unique_value_count", "range", "description"] }, "PetalWidthCm": { "properties": { "column_name": { "title": "Column Name", "type": "string" }, "data_type": { "title": "Data Type", "type": "string" }, "semantic_type": { "title": "Semantic Type", "type": "string" }, "sample_values": { "type": "array", "items": { "type": "number" } }, "null_count": { "title": "Null Count", "type": "integer" }, "null_percentage": { "type": "number", "description": "between 0.0 and 100.0" }, "unique_value_count": { "title": "Unique Value Count", "type": "integer" }, "range": { "type": "object", "properties": { "min": { "type": "number" }, "max": { "type": "number" } } }, "description": { "title": "Description", "type": "string" } }, "required": ["column_name", "data_type", "semantic_type", "sample_values", "null_count", "null_percentage", "unique_value_count", "range", "description"] }, "Species": { "properties": { "column_name": { "title": "Column Name", "type": "string" }, "data_type": { "title": "Data Type", "type": "string" }, "semantic_type": { "title": "Semantic Type", "type": "string" }, "sample_values": { "type": "array", "items": { "type": "string" } }, "null_count": { "title": "Null Count", "type": "integer" }, "null_percentage": { "type": "number", "title": "Null Percentage", "description": "between 0.0 and 100.0" }, "unique_value_count": { "title": "Unique Value Count", "type": "integer" }, "top_categories": { "properties": { "Iris-setosa": { "title": "Iris-setosa", "type": "integer" }, "Iris-versicolor": { "title": "Iris-versicolor", "type": "integer" }, "Iris-virginica": { "title": "Iris-virginica", "type": "integer" } }, "required": ["Iris-setosa", "Iris-versicolor", "Iris-virginica"] }, "range": { "type": "null" }, "description": { "title": "Description", "type": "string" } }, "required": ["column_name", "data_type", "semantic_type", "sample_values", "null_count", "null_percentage", "unique_value_count", "top_categories", "description"] } }, "required": ["Id", "SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", "Species"] } }, "required": ["file_level_metadata", "per_column_details"] }"""
# async def run_pandas_query_executor_workflow():
#     res = await workflow_for_pandas_query.ainvoke(
#         {"messages": [HumanMessage(content=content)]}
#     )
#     return res


# if __name__ == "__main__":
#     res = asyncio.run(
#         workflow_for_pandas_query()
#     )
#     print(res)
